spring.application.name=demo
server.port=8081

# OracleDB connection settings
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=HR
spring.datasource.password=hr
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.user.name=admin
spring.security.user.password=admin123

logging.level.root=INFO
logging.level.com.example.demo=DEBUG

logging.file.name=logs/demo.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n